### ISSUE TITLE
头像上传流程

### ISSUE THREAD

**Issue by ghost** [DjangoChinaOrg/Django-China-FE#36]

**Comment by tinyx** [comment]
我们的文件保存策略是什么？用Django的文件管理还是CDN？

头像上传的逻辑依赖于用使用哪个流程。上传完全由上传文件的流程来搞定，最后只是拿到URL以后使用users的API来更新url

**Comment by ghost** [comment]
头像存在服务器文件系统，头像会被压缩的很小，所以基本不会对服务器造成压力。无需使用cdn
